### ISSUE TITLE
Help with errors

### ISSUE THREAD

**Issue by rohankhaire-work** [MrNeRF/LichtFeld-Studio#309]
Hello, thank you for your work.

I have NVIDIA 4080 laptop gpu with 12GB of VRAM.
I built the code on the docker container. 
I tried to test this on the *Tanks and Trains Dataset* 

I got two errors -
- invalid render size
- CUDA unknown error

Could you please help me with them? Thank you.

``` bash
Parameter verification report:

Unknown parameters in JSON (will be ignored):
  - stop_refine_scale2d
Starting viewer mode...
Loading dataset from: data/tandt_db/tandt/train
SceneManager: Loading dataset: data/tandt_db/tandt/train
LoaderService initialized with 3 loaders
Using COLMAP loader for: data/tandt_db/tandt/train
[  0.0%] Loading COLMAP dataset...
Trying to load COLMAP in binary format
[ 20.0%] Reading camera parameters...
Training with 301 images 
[ 40.0%] Creating 301 cameras...
Dataset created with 301 images (split: 2)
[ 60.0%] Loading point cloud...
Loaded 182686 points from COLMAP
[100.0%] COLMAP loading complete
COLMAP dataset loaded successfully in 2035ms
  - 301 cameras
  - Scene center: [-0.097, 0.001, -0.006]
Dataset loaded successfully using COLMAP loader
Using point cloud with 182686 points
Scene scale: 2.4431043
Initialized SplatData with:
  - 182686 points
  - Max SH degree: 3
  - Total SH coefficients: 16
  - sh0 shape: [182686, 1, 3]
  - shN shape: [182686, 15, 3]
Using all 301 images for training (no evaluation)
Render mode: RGB
Visualization: enabled
Strategy: mcmc
Anti-aliasing: disabled
Failed to initialize CUDA-GL interop: Failed to register OpenGL texture with CUDA: unknown error
Falling back to CPU copy mode
CUDA-OpenGL interop framebuffer initialized successfully
CUDA-OpenGL interop enabled for rendering
[ViewportGizmo] Shaders created successfully
Successfully loaded font: /home/rohan/projects/gaussian-splatting-cuda/src/visualizer/resources/assets/JetBrainsMono-Regular.ttf with 3 characters
ERROR: Invalid render size!
[WindowManager] Window gained focus
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: unknown error
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at /pytorch/c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xb0 (0x754c058e8de0 in /home/rohan/projects/gaussian-splatting-cuda/external/libtorch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xfa (0x754c0587646e in /home/rohan/projects/gaussian-splatting-cuda/external/libtorch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x3cc (0x754c0657ee7c in /home/rohan/projects/gaussian-splatting-cuda/external/libtorch/lib/libc10_cuda.so)
frame #3: void at::native::gpu_kernel_impl_nocast<at::native::FillFunctor<float> >(at::TensorIteratorBase&, at::native::FillFunctor<float> const&) + 0x4f3 (0x754b4917fc13 in /home/rohan/projects/gaussian-splatting-cuda/external/libtorch/lib/libtorch_cuda.so)
frame #4: void at::native::gpu_kernel_impl<at::native::FillFunctor<float> >(at::TensorIteratorBase&, at::native::FillFunctor<float> const&) + 0x2c5 (0x754b49182dd5 in /home/rohan/projects/gaussian-splatting-cuda/external/libtorch/lib/libtorch_cuda.so)
frame #5: void at::native::gpu_kernel<at::native::FillFunctor<float> >(at::TensorIteratorBase&, at::native::FillFunctor<float> const&) + 0x35b (0x754b4918353b in /home/rohan/projects/gaussian-splatting-cuda/external/libtorch/lib/libtorch_cuda.so)
frame #6: <unknown function> + 0x1d64cd2 (0x754b49164cd2 in /home/rohan/projects/gaussian-splatting-cuda/external/libtorch/lib/libtorch_cuda.so)
frame #7: at::native::fill_kernel_cuda(at::TensorIterator&, c10::Scalar const&) + 0x34 (0x754b491669d4 in /home/rohan/projects/gaussian-splatting-cuda/external/libtorch/lib/libtorch_cuda.so)
frame #8: <unknown function> + 0x207f53f (0x754bcb07f53f in /home/rohan/projects/gaussian-splatting-cuda/external/libtorch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x39d42d3 (0x754b4add42d3 in /home/rohan/projects/gaussian-splatting-cuda/external/libtorch/lib/libtorch_cuda.so)
frame #10: <unknown function> + 0x5f4fbbd (0x754bcef4fbbd in /home/rohan/projects/gaussian-splatting-cuda/external/libtorch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x56497e9 (0x754bce6497e9 in /home/rohan/projects/gaussian-splatting-cuda/external/libtorch/lib/libtorch_cpu.so)
frame #12: at::_ops::fill__Scalar::call(at::Tensor&, c10::Scalar const&) + 0x186 (0x754bcb983c26 in /home/rohan/projects/gaussian-splatting-cuda/external/libtorch/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0xa1837 (0x58af1a87c837 in ./build/gaussian_splatting_cuda)
frame #14: <unknown function> + 0xb61db (0x58af1a8911db in ./build/gaussian_splatting_cuda)
frame #15: <unknown function> + 0x1e379c (0x58af1a9be79c in ./build/gaussian_splatting_cuda)
frame #16: <unknown function> + 0x2a0d9f (0x58af1aa7bd9f in ./build/gaussian_splatting_cuda)
frame #17: <unknown function> + 0x2c328b (0x58af1aa9e28b in ./build/gaussian_splatting_cuda)
frame #18: <unknown function> + 0x1ced17 (0x58af1a9a9d17 in ./build/gaussian_splatting_cuda)
frame #19: <unknown function> + 0x1cddbe (0x58af1a9a8dbe in ./build/gaussian_splatting_cuda)
frame #20: <unknown function> + 0x1256e3 (0x58af1a9006e3 in ./build/gaussian_splatting_cuda)
frame #21: <unknown function> + 0x1235c1 (0x58af1a8fe5c1 in ./build/gaussian_splatting_cuda)
frame #22: <unknown function> + 0x12b1a0 (0x58af1a9061a0 in ./build/gaussian_splatting_cuda)
frame #23: <unknown function> + 0x12928e (0x58af1a90428e in ./build/gaussian_splatting_cuda)
frame #24: <unknown function> + 0x127798 (0x58af1a902798 in ./build/gaussian_splatting_cuda)
frame #25: <unknown function> + 0x15d77e (0x58af1a93877e in ./build/gaussian_splatting_cuda)
frame #26: <unknown function> + 0x15d63c (0x58af1a93863c in ./build/gaussian_splatting_cuda)
frame #27: <unknown function> + 0x1258e0 (0x58af1a9008e0 in ./build/gaussian_splatting_cuda)
frame #28: <unknown function> + 0x32bb43 (0x58af1ab06b43 in ./build/gaussian_splatting_cuda)
frame #29: <unknown function> + 0x32bd02 (0x58af1ab06d02 in ./build/gaussian_splatting_cuda)
frame #30: <unknown function> + 0x6174a (0x58af1a83c74a in ./build/gaussian_splatting_cuda)
frame #31: <unknown function> + 0x2a1ca (0x754b46f9a1ca in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #32: __libc_start_main + 0x8b (0x754b46f9a28b in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #33: <unknown function> + 0x61565 (0x58af1a83c565 in ./build/gaussian_splatting_cuda)

Aborted (core dumped)
```

**Comment by rohankhaire-work** [comment]
I solved the problem. I had to switch the Nvidia PRIME profile from on-demand to performance mode. Then restart and it worked.
